allows batch upoads

diff --git a/uploadtocloud b/uploadtocloud
--- a/uploadtocloud
+++ b/uploadtocloud
@@ -13,8 +13,6 @@ setup() {
 
 copy_file() {
 
-    echo "please enter the path to target file :" 
-    read targetpath
     storage_array=($( az storage account list --query '[].name' --output tsv))
         if [[ ${#storage_array[@]} -eq 1 ]]; then
             storageAccount=${storage_array[0]}
@@ -54,48 +52,76 @@ copy_file() {
     fi
     echo "resourcegroup is $resourceGroup , account Key is $accountKey , containers are $container"
 
+    #single or batch upload
+
+    echo " how many files do you want to upload ? :"
+    read numfiles
+
+    if [[ "&numfiles" -eq 1 ]]; then
+
+        echo "please enter the path to target file :" 
+        read targetpath
+
     #check if file already exists
     echo "please enter name for blob :" 
     read blob_name
 
     existing_blob=$(az storage blob exists --account-name $storageAccount --account-key $accountKey --container-name $container --name $blob_name --output tsv)
 
-    if [ "$existing_blob" == "True" ]; then
+        if [ "$existing_blob" == "True" ]; then
     
         # Handle synchronization (prompt user to overwrite, skip, or rename)
         echo "File $blob_name already exists in the cloud."
         read -p "Do you want to overwrite, skip, or rename? (o/s/r): " choice
 
-        case $choice in
-            o)
-                echo "Overwriting the existing file..."
-                az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name --overwrite "true"
-                if [ $? -eq 0 ]; then
-                echo "The file has been successfully uploaded."
-                else
-                error_message=$(az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name myblob 2>&1)
-                echo "Error uploading the file: $error_message"
-                fi
-                ;;
-            s)
-                echo "Skipping the file..."
-                return
-                ;;
-            r)
-                read -p "Enter a new name for the file: " new_name
-                blob_name=$new_name
-                echo "Renaming the file to $blob_name..."
-                az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name
+            case $choice in
+                o)
+                    echo "Overwriting the existing file..."
+                    az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name --overwrite "true"
+                    if [ $? -eq 0 ]; then
+                    echo "The file has been successfully uploaded."
+                    else
+                    error_message=$(az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name myblob 2>&1)
+                    echo "Error uploading the file: $error_message"
+                    fi
+                    ;;
+                s)
+                    echo "Skipping the file..."
+                    return
+                    ;;
+                r)
+                    read -p "Enter a new name for the file: " new_name
+                    blob_name=$new_name
+                    echo "Renaming the file to $blob_name..."
+                    az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name
 
-                ;;
-            *)
-                echo "Invalid choice. Skipping the file..."
-                return
-                ;;
-        esac
+                    ;;
+                *)
+                    echo "Invalid choice. Skipping the file..."
+                    return
+                    ;;
+            esac
+        else
+            echo "uploading the file.. "
+            az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name
+        fi
+
     else
+        echo " all the files in a directory?[true/false]"
+        read directory
+
+        if [[ ""$directory"" == "true" ]]; then
+        echo "enter the path to the directory"
+        read dirpath
         echo "uploading the file.. "
-        az storage blob upload --account-name $storageAccount --account-key $accountKey --container-name $container --file $targetpath --name $blob_name
+        az storage blob upload-batch -d $container -s $dirpath --account-name $storageAccount --account-key $accountKey 
+
+        else
+        echo "enter pattern [eg *.txt]"
+        read pattern
+        echo "uploading the file.. "
+        az storage blob upload-batch -d $container -s $dirpath --account-name $storageAccount --account-key $accountKey --container-name --pattern "*.py"
+        fi
     fi
 
 
